spring.application.name=demo5

spring.datasource.url=jdbc:mysql://localhost:3306/demoproduct
spring.datasource.username=root
spring.datasource.password=
# Cấu hình tự động cập nhật bảng trong database dựa theo Entity
spring.jpa.hibernate.ddl-auto=update